create schema if not exists confirmation_code;

create table if not exists confirmation_code.confirmation_codes(
    id bigint generated by default as identity primary key ,
    code int not null ,
    expiration_date timestamp not null ,
    type varchar not null ,
    user_id bigint not null
);